baseURL = "http://example.org/"
languageCode = "en-us"
title = "Acme Corporation"
theme = "AcmeTheme"
enableEmoji = true
enbleGitInfo = true

sectionPagesMenu = "sections"
paginate = 3

ignoreErrors = ["error-remote-getjson"]