color = "#DC2626"
copyright = "Copyright &copy; 2022 Acme Corporation. All Rights Reserved."
style = "blue"
logo = "/assets/image/logo.png"
logo_small = "/assets/image/logo.png"
netlifyCommentForm = "6230753b60f8cf0009ccf4f8"
RemoveFormOnSubmission = "true"
Latex2Svg = "https://hugosamplesite.netlify.app/.netlify/functions/latex2svg"

[TermsAndPrivacy]
company_name = "Acme Corporation"
contact_email = "contact@example.org"
website = "https://hugoinaction.com"
contact_dpo_email = "dpo@hugoinaction.com"
contact_dpo_phone = 9_999_999_999
